name: presensi
version: 1.0.4+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.2
  dropdown_search: ^3.0.1
  firebase_auth: ^3.3.17
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.3
  get: 4.6.3
  iconly: ^1.0.1
  image_picker: ^0.8.5
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

flutter_native_splash:
  color: "#0C3469"
  image: assets/images/logo.png
